server:
  port: 8881
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanlonglong/aispringcloud.git
          searchPaths: config
          username: wanlonglong
          password: de8326989
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/